name: Create daily release

on:
  schedule:
    - cron: '1 0 * * *'  # Läuft täglich um 00:01 UTC
  workflow_dispatch:

jobs:
  create-daily-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract latest 5000 characters from CHANGELOG.md
        run: |
          MAX_SIZE=5000
          tail -c "$MAX_SIZE" CHANGELOG.md > changelog_cropped.md

      - name: Parse CHANGELOG.md for yesterday's entry and create a new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          YESTERDAY=$(date -u --date="yesterday" +%Y-%m-%d)
          
          # Extrahiere die Sektion für das gestrige Datum
          awk -v date="## $YESTERDAY" '
            $0 ~ date {found=1; next} 
            found && /^## [0-9]{4}-[0-9]{2}-[0-9]{2}/ {exit} 
            found
          ' changelog_cropped.md > changelog_tmp.md

          echo "=== Extracted Changelog ==="
          cat changelog_tmp.md
          echo "==========================="

          if [ ! -s changelog_tmp.md ]; then
            echo "No changes found for $YESTERDAY, skipping release."
            exit 0
          fi

          echo "Creating GitHub release for $YESTERDAY..."
          gh release create "$YESTERDAY" -t "$YESTERDAY" -F changelog_tmp.md
